"""
Plot violin + scatter comparison from exported keypoint prediction txt files.

Expected txt format is generated by tools/inference.py and tools/infer_offset.py
with --save-keypoints:

sample_index  sample_id  keypoint_id  pred_x  pred_y  pred_z  gt_x  gt_y  gt_z  error
"""

import argparse
import csv
import glob
import os
from collections import defaultdict

import matplotlib.pyplot as plt
import numpy as np
# 设置 matplotlib 的全局字体为 Times New Roman
plt.rcParams['font.family'] = 'Times New Roman'
# 解决负号 '-' 显示为方块的问题
plt.rcParams['axes.unicode_minus'] = False 

# 同步覆盖 seaborn 的主题字体配置，确保使用 sns 绘制的图表字体一致
# sns.set_theme(style="whitegrid", font='Times New Roman')

def get_args():
    parser = argparse.ArgumentParser(description="Plot keypoint mean-error violin/scatter comparison.")
    parser.add_argument(
        "--inputs",
        nargs="+",
        required=True,
        help=(
            "Input specs in the form label=path. Path can be one exported txt file "
            "or a directory containing txt files."
        ),
    )
    parser.add_argument("--output", default=None, help="Output figure path, e.g. outputs/keypoint_violin.png")
    parser.add_argument("--csv-output", default=None, help="Optional csv path for per-sample mean errors.")
    parser.add_argument("--title", default="Keypoint Error Comparison", help="Figure title.")
    parser.add_argument("--unit", default="mm", help="Error unit shown on the y-axis.")
    parser.add_argument("--figsize", nargs=2, type=float, default=(12.0, 6.0), metavar=("W", "H"))
    parser.add_argument("--dpi", type=int, default=1200, help="Saved figure DPI.")
    parser.add_argument("--seed", type=int, default=0, help="Random seed for scatter jitter.")
    parser.add_argument("--jitter", type=float, default=0.06, help="Scatter x-axis jitter width.")
    parser.add_argument("--show", action="store_true", help="Show the figure after saving.")
    return parser.parse_args()


def parse_input_spec(spec):
    if "=" in spec:
        label, path = spec.split("=", 1)
        label = label.strip()
        path = path.strip()
    else:
        path = spec.strip()
        label = os.path.splitext(os.path.basename(os.path.normpath(path)))[0]
    if not label:
        raise ValueError(f"Empty label in input spec: {spec}")
    if not path:
        raise ValueError(f"Empty path in input spec: {spec}")
    return label, path


def expand_input_path(path):
    if os.path.isdir(path):
        files = sorted(glob.glob(os.path.join(path, "*.txt")))
        if not files:
            raise FileNotFoundError(f"No txt files found in directory: {path}")
        return files
    if not os.path.isfile(path):
        raise FileNotFoundError(f"Input file not found: {path}")
    return [path]


def read_exported_keypoints(path):
    groups = defaultdict(list)
    with open(path, "r", encoding="utf-8") as f:
        data_lines = [line for line in f if line.strip() and not line.startswith("#")]
    if not data_lines:
        raise ValueError(f"No data rows found in: {path}")

    reader = csv.DictReader(data_lines, delimiter="\t")
    required = {"sample_index", "sample_id", "keypoint_id", "pred_x", "pred_y", "pred_z", "gt_x", "gt_y", "gt_z"}
    missing = required - set(reader.fieldnames or [])
    if missing:
        raise ValueError(f"{path} is missing columns: {sorted(missing)}")

    for row in reader:
        sample_key = (row["sample_index"], row["sample_id"])
        pred = np.array([float(row["pred_x"]), float(row["pred_y"]), float(row["pred_z"])], dtype=np.float64)
        gt = np.array([float(row["gt_x"]), float(row["gt_y"]), float(row["gt_z"])], dtype=np.float64)
        error = np.linalg.norm(pred - gt)
        if np.isfinite(error):
            groups[sample_key].append(float(error))

    sample_errors = []
    for (sample_index, sample_id), errors in sorted(groups.items(), key=lambda item: int(item[0][0])):
        if errors:
            sample_errors.append(
                {
                    "sample_index": int(sample_index),
                    "sample_id": sample_id,
                    "mean_error": float(np.mean(errors)),
                    "num_keypoints": len(errors),
                }
            )
    if not sample_errors:
        raise ValueError(f"No finite sample errors found in: {path}")
    return sample_errors


def load_labeled_errors(input_specs):
    labeled = []
    for spec in input_specs:
        label, path = parse_input_spec(spec)
        files = expand_input_path(path)
        rows = []
        for file_path in files:
            rows.extend(read_exported_keypoints(file_path))
        values = np.array([row["mean_error"] for row in rows], dtype=np.float64)
        labeled.append((label, values, rows))
        print(
            f"{label}: samples={len(values)}, mean={values.mean():.4f}, "
            f"std={values.std():.4f}, source_files={len(files)}"
        )
    return labeled


def save_error_csv(labeled, csv_path):
    output_dir = os.path.dirname(csv_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    with open(csv_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["label", "sample_index", "sample_id", "mean_error", "num_keypoints"])
        for label, _, rows in labeled:
            for row in rows:
                writer.writerow(
                    [label, row["sample_index"], row["sample_id"], f"{row['mean_error']:.8f}", row["num_keypoints"]]
                )
    print(f"=> Saved per-sample mean errors to: {csv_path}")


def plot_violin_scatter(labeled, args):
    labels = [item[0] for item in labeled]
    data = [item[1] for item in labeled]
    positions = np.arange(1, len(data) + 1)
    rng = np.random.default_rng(args.seed)

    fig, ax = plt.subplots(figsize=tuple(args.figsize))
    violin = ax.violinplot(data, positions=positions, showmeans=True, showextrema=True, widths=0.72)
    for body in violin["bodies"]:
        body.set_facecolor("#8fb9d9")
        body.set_edgecolor("#315f7d")
        body.set_alpha(0.45)
    for key in ("cmeans", "cmins", "cmaxes", "cbars"):
        if key in violin:
            violin[key].set_color("#315f7d")
            violin[key].set_linewidth(1.2)

    for pos, values in zip(positions, data):
        jitter = rng.normal(loc=0.0, scale=args.jitter, size=len(values))
        ax.scatter(
            np.full(len(values), pos) + jitter,
            values,
            s=18,
            alpha=0.65,
            color="#d95f02",
            edgecolors="white",
            linewidths=0.3,
        )

    ax.set_title(args.title)
    ax.set_ylabel(f"Mean Error over Keypoints ({args.unit})")
    ax.set_xticks(positions)
    ax.set_xticklabels(labels, rotation=20, ha="right")
    ax.grid(axis="y", linestyle="--", alpha=0.35)
    ax.set_axisbelow(True)
    fig.tight_layout()

    if args.output:
        output_dir = os.path.dirname(args.output)
        if output_dir:
            os.makedirs(output_dir, exist_ok=True)
        fig.savefig(args.output, dpi=args.dpi, bbox_inches="tight")
        print(f"=> Saved figure to: {args.output}")

    if args.show or not args.output:
        plt.show()
    plt.close(fig)


def main():
    args = get_args()
    labeled = load_labeled_errors(args.inputs)
    if args.csv_output:
        save_error_csv(labeled, args.csv_output)
    plot_violin_scatter(labeled, args)

"""
python tools/plot_keypoint_error_violin.py \
    --inputs "outputs/keypoints/octformer_direct.txt" "outputs/keypoints/octformer_offset.txt" \
             "outputs/keypoints/ptv3_direct.txt" "outputs/keypoints/ptv3_offset.txt" \
             "outputs/keypoints/swin3d_direct.txt" "outputs/keypoints/swin3d_offset.txt" \
    --output "outputs/keypoint_violin.png" \
    --csv-output "outputs/keypoint_errors.csv" \
    --title "Keypoint Error Comparison" \
    --unit "mm" \
    --figsize 12 6 \
    --dpi 1200 
"""
if __name__ == "__main__":
    main()
